import { Product } from "../redux/slices/appSlice";

const productData: Product[] = [
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER BASKET WITH PINK ROSES",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 75.50,
        stock: 300,
        sold: 130,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/221-home_default/flower-basket-with-pink-roses.jpg",
            "https://www.zieduserviss.lv/220-large_default/flower-basket-with-pink-roses.jpg"
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF PINK ROSES R1",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 195.00,
        stock: 300,
        sold: 35,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1473-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1470-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1472-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "BOUQUET OF RED TULIPS",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 35.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1144-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1135-large_default/flower-box-autumn-kiss.jpg",
            "https://www.zieduserviss.lv/1136-large_default/flower-box-autumn-kiss.jpg",
        ],
    },
    {
        _id: "string",
        name: "FLOWER HEART",
        description: "Please, be aware that the picture is illustrative because flowers are seasonal. If specific flowers are not available, we will replace them with others, maintaining the bouquet style and colour gamut. Our professional florists always make sure that the compositions are tasteful, beautiful and the customers are satisfied. If you want to clarify whether the flowers shown in the picture are currently available, please contact us by phone - +371 26621676 or e-mail - karkade@karkade.lv.",
        price: 60.00,
        stock: 300,
        sold: 38,
        category: "string",
        images: [
            "https://www.zieduserviss.lv/1099-large_default/heart-of-white-flowers.jpg",
            "https://www.zieduserviss.lv/1100-large_default/heart-of-white-flowers.jpg",
        ],
    },
];

export default productData;